name: Scraping Horarios SIAU

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Usuario de inicio de sesión'
        required: true
      password:
        description: 'Contraseña del sistema'
        required: true
      base-url:
        description: 'URL base del sistema'
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar navegador Chromium
        run: npx playwright install chromium

      - name: Ejecutar acción personalizada de scraping
        uses: ./.github/actions/scrapeSchedules
        with:
          username: ${{ github.event.inputs.username }}
          password: ${{ github.event.inputs.password }}
          base-url: ${{ github.event.inputs['base-url'] }}
